# Generated by Django 3.2.8 on 2022-02-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0003_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
