# Generated by Django 3.2.8 on 2022-02-22 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapi', '0005_alter_loginhistory_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
